### ISSUE TITLE
ModuleNotFoundError: No module named 'snake_gym.envs'

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [vivek3141/snake-gym#2]
I am using the pip package snake-gym 1.8. My code is exactly as described on https://pypi.org/project/snake-gym/

```
import gym
import snake_gym
env = gym.make("snake-v0")
```

Full traceback:

```
Traceback (most recent call last):
  File ".../openai/test.py", line 4, in <module>
    env = gym.make("snake-v0")
  File "...\venv\lib\site-packages\gym\envs\registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "...\venv\lib\site-packages\gym\envs\registration.py", line 87, in make
    env = spec.make(**kwargs)
  File "...\venv\lib\site-packages\gym\envs\registration.py", line 58, in make
    cls = load(self.entry_point)
  File "...\venv\lib\site-packages\gym\envs\registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'snake_gym.envs'
```

Language: Python 3.7 

IDE: Pycharm 2019.3.3

**Comment by vvvlc** [comment]
Hi 
I had same problem I used
```sh
pipenv install -e git+https://github.com/grantsrb/Gym-Snake.git#egg=snake_gym
```
and this to test code
```python
import gym
import gym_snake
env = gym.make("snake-v0")
env.reset()
env.render()

for _ in range(500):
    env.render()
    env.step(1)
```

**Comment by thediscordhealer** [comment]
same problem please help

**Comment by AbdelrahmanAbdelgwad** [comment]
This command (pipenv install -e git+https://github.com/grantsrb/Gym-Snake.git#egg=snake_gym) is not working with me on anaconda

it outputs this 
![image](https://user-images.githubusercontent.com/93412453/148665471-f0c3ce45-e348-4bc7-8350-3c038f872b30.png)

**Comment by DrKakku** [comment]
> I am using the pip package snake-gym 1.8. My code is exactly as described on https://pypi.org/project/snake-gym/
> 
> ```
> import gym
> import snake_gym
> env = gym.make("snake-v0")
> ```
> 
> Full traceback:
> 
> ```
> Traceback (most recent call last):
>   File ".../openai/test.py", line 4, in <module>
>     env = gym.make("snake-v0")
>   File "...\venv\lib\site-packages\gym\envs\registration.py", line 142, in make
>     return registry.make(id, **kwargs)
>   File "...\venv\lib\site-packages\gym\envs\registration.py", line 87, in make
>     env = spec.make(**kwargs)
>   File "...\venv\lib\site-packages\gym\envs\registration.py", line 58, in make
>     cls = load(self.entry_point)
>   File "...\venv\lib\site-packages\gym\envs\registration.py", line 17, in load
>     mod = importlib.import_module(mod_name)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'snake_gym.envs'
> ```
> 
> Language: Python 3.7
> 
> IDE: Pycharm 2019.3.3

I had the same Issue and to resolve it I had to perform the following steps

- Install the package using the pip package manager ```pip install snake-gym```
- Download the repository from GitHub 
- copy the env folder from (snake-gym)[https://github.com/vivek3141/snake-gym/tree/master/snake_gym] in your clipboard
- go to the location where the package was installed (You can usually find it using ```pip show snake_gym```)
- paste the env folder in the package folder

That should help fix it
